#wap to take two numbers as input now find summation, subtration,multiplication and division to two numbers
a=25
b=26
a=int(input("enter the first no: "))
b=int(input("enter the second no: "))
sum=a+b
sub=a-b
mul=a*b
div=a/b
print("SUB = ",sub)
print("SUM = ",sum)
print("MUL = ",mul)
print("DIV = ",div)
a=float(input("enter the first no: "))
b=float(input("enter the second no: "))
sum=a+b
sub=a-b
mul=a*b
div=a/b
print("SUB = ",sub)
print("SUM = ",sum)
print("MUL = ",mul)
print("DIV = ",div)
a=eval(input("enter the first no: "))
b=eval(input("enter the second no: "))
sum=a+b
sub=a-b
mul=a*b
div=a/b
print("SUB = ",sub)
print("SUM = ",sum)
print("MUL = ",mul)
print("DIV = ",div)